name: hello world
on:
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY
  build-program:
    runs-on: ubuntu-latest
    steps:
      - name: print GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: build main
        run: gcc -o my_app src/main.c src/functions.c -Iinclude