name: hello world
on:
  push:
    branches: [develop]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY
  print-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: print GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: print GITHUB_ENV
        run: echo $GITHUB_ENV
  build-program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: gcc -o main main.c functions.c -I.
      - name: Test
        run: ./main
      - name: Build example
        run: gcc -o example example.c
      - name: Test example
        run: ./example
  deploy:
    needs: build-program
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: |
          echo "Deploying application....."
          # Add your deployment commands here